# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
et:
  languageCode: et
  contentDir: content/et
  title: LasteFotograaf
  params:
    description: Vastündinu ja lapseootuse fotograaf Tallinnas - Viktoria Iljin
  menu:
    main:
      - name: Minust
        url: '#about'
        weight: 30
      - name: Portfoolio ja hinnad
        url: '#projects'
        weight: 10
      - name: Blogi
        url: '#posts'
        weight: 20
      - name: Kontakt
        url: '#contact'
        weight: 40
ru:
  languageCode: ru
  contentDir: content/ru
  title: Виктория Ильин
  params:
    description: Фотограф новорожденных и беременных в Таллинне - Виктория Ильин
  menu:  
    main:
      - name: Обо мне
        url: '#about'
        weight: 30
      - name: Портфолио и цены
        url: '#projects'
        weight: 10
      - name: Блог
        url: '#posts'
        weight: 20
      - name: Контакт
        url: '#contact'
        weight: 40
en:
  languageCode: en
  contentDir: content/en
  title: Viktoria Iljin
  params:
    description: Newborn and pregnancy photographer in Tallinn - Viktoria Iljin
  menu:
    main:
      - name: About me
        url: '#about'
        weight: 30
      - name: Portfolio and prices
        url: '#projects'
        weight: 10
      - name: Blog
        url: '#posts'
        weight: 20
      - name: Contact
        url: '#contact'
        weight: 40

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
