# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

theme: Strawberry
day_night: false
font: 'native'
font_size: L

# SEO

site_type: LocalBusiness
local_business_type: 'ProfessionalService'
org_name: 'Fotograaf Viktoria Iljin'
description: 'Vastündinu ja lapseootuse fotograaf Tallinnas - Viktoria Iljin'
twitter: 'lastefoto'

# Contact (edit or remove options as required)

email: lastefoto@gmail.com
phone: 37255599546
address:
  street: Peterburi tee 46
  city: Tallinn
  region: Harjumaa
  postcode: '11415'
  country: Estonia
  country_code: EE
coordinates:
  latitude: '59.426760'
  longitude: '24.818860'
directions: 'Boonus Meedia OÜ (registrikood 11268326)'
office_hours: ''
appointment_url: ''
contact_links:
  - icon: instagram
    icon_pack: fab
    name: 'viktoriailjin'
    link: 'https://www.instagram.com/viktoriailjin/'
  - icon: facebook
    icon_pack: fab
    name: 'LasteFoto'
    link: 'https://www.facebook.com/LasteFoto/'

# Site header

main_menu:
  enable: true
  align: r
  show_logo: true
  show_language: true
  show_day_night: false
  show_search: true
  highlight_active_link: true

# Localization

date_format: '2006-01-02'
time_format: '15:04'
address_format: de

# Site features

highlight: false
highlight_languages:
  - r
math: false
diagram: false
privacy_pack: false
edit_page:
  repo_url: ''
  content_dir: ''
  repo_branch: main
  editable:
    page: false
    post: false
    book: false
show_related:
  book: true
  page: true
  post: true
  project: true
  publication: true
  event: true
reading_time: false
section_pager: false
docs_section_pager: true
sharing: false
copyright_license:
  enable: false
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'
abstract_length: 135
plugins_js: []
avatar:
  gravatar: false
  shape: circle
publications:
  date_format: January 2006
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
breadcrumb:
  page_types:
    book: true
comments:
  provider: ''
  commentable:
    post: true
    page: true
    book: true
    project: true
    publication: true
    event: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  provider: ''
  api_key: ''
  zoom: 15
marketing:
  google_analytics: 'UA-111369930-1'
  google_tag_manager: 'GTM-TC56VG7'
  google_site_verification: 'rPODh7GdZ4rJqu3xUqF3-HbWR3dxQ_fHqdTmr7HlHBk'
  baidu_site_verification: ''
  baidu_tongji: ''
cms:
  netlify_cms: false
icon:
  pack:
    ai: false
